"""initial

Revision ID: 4550095e60ac
Revises: 
Create Date: 2022-08-25 00:09:05.506319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4550095e60ac"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
